# frozen_string_literal: true

require 'open3'

module Exwiw
  module Adapter
    class MysqlAdapter < Base
      def build_query(table, dump_target, table_by_name)
        Exwiw::QueryAstBuilder.run(table.name, table_by_name, dump_target, @logger)
      end

      def execute(query_ast)
        sql = commented_sql(query_ast)

        @logger.debug("  Executing SQL: \n#{sql}")
        connection.query(sql).rows
      end

      def explain(query_ast)
        sql = commented_sql(query_ast)

        @logger.debug("  Executing EXPLAIN: \n#{sql}")
        result = connection.query("EXPLAIN #{sql}")
        result.rows.each_with_index.flat_map do |row, i|
          ["*************************** #{i + 1}. row ***************************"] +
            result.fields.zip(row).map { |k, v| "#{k}: #{v}" }
        end.join("\n")
      end

      def dump_schema(ordered_tables, output_path)
        table_names = ordered_tables.map(&:name)
        if table_names.empty?
          File.write(output_path, "-- Auto-generated by exwiw. No tables in scope.\n")
          return
        end

        # The mysqldump binary is invoked directly (not via the mysql2/trilogy
        # driver), so point EXWIW_MYSQLDUMP at a specific binary when the one on
        # PATH is incompatible with the server — e.g. a MySQL 9.x client whose
        # mysqldump cannot load `mysql_native_password` ("plugin ... cannot be
        # loaded", exit 2) against a server still using that auth plugin.
        mysqldump_bin = ENV['EXWIW_MYSQLDUMP']
        mysqldump_bin = 'mysqldump' if mysqldump_bin.nil? || mysqldump_bin.empty?

        # MariaDB's mysqldump does not recognise the MySQL-specific
        # --set-gtid-purged flag and exits with code 7.
        gtid_flags = mariadb_mysqldump?(mysqldump_bin) ? [] : ['--set-gtid-purged=OFF']

        cmd = [
          mysqldump_bin,
          "--host=#{@connection_config.host}",
          "--port=#{@connection_config.port}",
          "--user=#{@connection_config.user}",
          '--no-data',
          '--skip-add-drop-table',
          '--skip-comments',
          '--skip-set-charset',
          '--no-tablespaces', # skip tablespace query that requires PROCESS privilege (unavailable on managed MySQL like RDS)
          *gtid_flags,
          '--compact',
          @connection_config.database_name,
          *table_names,
        ]
        env = { 'MYSQL_PWD' => @connection_config.password.to_s }

        @logger.debug("  Running #{mysqldump_bin} for #{table_names.size} table(s)...")
        stdout, stderr, status =
          begin
            Open3.capture3(env, *cmd)
          rescue Errno::ENOENT
            raise "Failed to run `#{mysqldump_bin}`. Ensure the mysql client is installed and on PATH, " \
                  "or set EXWIW_MYSQLDUMP to a mysqldump binary."
          end
        unless status.success?
          if stderr.include?('command not found') || stderr.empty?
            raise "Failed to run `#{mysqldump_bin}`. Ensure the mysql client is installed and on PATH, " \
                  "or set EXWIW_MYSQLDUMP to a mysqldump binary. stderr: #{stderr}"
          end
          raise "mysqldump failed (exit #{status.exitstatus}): #{stderr}"
        end

        idempotent = DdlPostprocessor.add_if_not_exists_to_create_table(stdout)

        File.open(output_path, 'w') do |file|
          file.puts("-- Auto-generated by exwiw via mysqldump. Idempotent CREATE TABLE statements for mysql.")
          file.puts("SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;")
          file.puts
          file.puts(idempotent)
          file.puts("SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;")
        end
        @logger.info("  Wrote schema for #{table_names.size} table(s) to #{output_path}.")
      end

      def pre_insert_sql(_table)
        "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;"
      end

      def post_insert_sql(_table)
        "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;"
      end

      def to_bulk_insert(results, table)
        table_name = table.name

        value_list = results.map do |row|
          quoted_values = row.map do |value|
            escape_value(value)
          end
          "(" + quoted_values.join(', ') + ")"
        end
        values = value_list.join(",\n")

        if table.rails_managed?
          "INSERT INTO `#{table_name}` VALUES\n#{values};"
        else
          column_names = table.columns.map { |c| "`#{c.name}`" }.join(', ')
          "INSERT INTO `#{table_name}` (#{column_names}) VALUES\n#{values};"
        end
      end

      def to_bulk_delete(select_query_ast, table)
        raise NotImplementedError unless select_query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "DELETE FROM #{select_query_ast.from_table_name}"

        if select_query_ast.join_clauses.empty?
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          compiled_where_conditions = select_query_ast.
            where_clauses.
            select { |where| where.is_a?(Exwiw::QueryAst::WhereClause) }.
            map do |where|
            compile_where_condition(where, select_query_ast.from_table_name)
          end

          if compiled_where_conditions.size > 0
            sql += "\nWHERE "
            sql += compiled_where_conditions.join(' AND ')
          end
          sql += ";"

          return sql
        end

        subquery_ast = Exwiw::QueryAst::Select.new
        first_join = select_query_ast.join_clauses.first.clone

        subquery_ast.from(first_join.join_table_name)
        primay_key_col = table.columns.find { |col| col.name == table.primary_key }
        subquery_ast.select([primay_key_col])
        select_query_ast.join_clauses[1..].each do |join|
          subquery_ast.join(join)
        end
        first_join.where_clauses.each do |where|
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          subquery_ast.where(where) if where.is_a?(Exwiw::QueryAst::WhereClause)
        end

        foreign_key = first_join.foreign_key
        subquery_sql = compile_ast(subquery_ast)
        sql += "\nWHERE #{select_query_ast.from_table_name}.#{foreign_key} IN (#{subquery_sql})"

        # first_join.base_where_clauses holds conditions on the outer
        # delete-target table (from_table_name), such as a polymorphic type
        # column. They are not part of the subquery, so add them to the outer
        # WHERE. This prevents deleting rows that belong to a different
        # polymorphic type.
        first_join.base_where_clauses.each do |where|
          next unless where.is_a?(Exwiw::QueryAst::WhereClause)

          sql += " AND #{compile_where_condition(where, select_query_ast.from_table_name)}"
        end
        sql += ";"

        sql
      end

      def compile_ast(query_ast)
        raise NotImplementedError unless query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "SELECT "
        sql += if query_ast.select_all
                 "*"
               else
                 query_ast.columns.map { |col| compile_column_name(query_ast, col) }.join(', ')
               end
        sql += " FROM #{query_ast.from_table_name}"

        query_ast.join_clauses.each do |join|
          sql += " JOIN #{join.join_table_name} ON #{join.base_table_name}.#{join.foreign_key} = #{join.join_table_name}.#{join.primary_key}"

          join.where_clauses.each do |where|
            compiled_where_condition = compile_where_condition(where, join.join_table_name)
            sql += " AND #{compiled_where_condition}"
          end

          # base_where_clauses is compiled against the joined-from table
          # (base_table_name), e.g. the type-column filter on a polymorphic
          # source table.
          join.base_where_clauses.each do |where|
            compiled_where_condition = compile_where_condition(where, join.base_table_name)
            sql += " AND #{compiled_where_condition}"
          end
        end

        if query_ast.where_clauses.any?
          sql += " WHERE "
          sql += query_ast.where_clauses.map { |where| compile_where_condition(where, query_ast.from_table_name) }.join(' AND ')
        end

        sql
      end

      private def compile_where_condition(where_clause, table_name)
        # Use as it is if it's a raw query
        return where_clause if where_clause.is_a?(String)

        key = "#{table_name}.#{where_clause.column_name}"

        if where_clause.operator == :eq
          values = where_clause.value.map { |v| escape_value(v) }

          if values.size == 1
            "#{key} = #{values.first}"
          else
            "#{key} IN (#{values.join(', ')})"
          end
        elsif where_clause.operator == :in_subquery
          "#{key} IN (#{compile_subquery(where_clause.value)})"
        else
          raise "Unsupported operator: #{where_clause.operator}"
        end
      end

      private def compile_subquery(subquery)
        # A SelectSubquery wraps a full Select (the referencing table's
        # extraction query, projected to a foreign key); compile it as-is.
        return compile_ast(subquery.query) if subquery.is_a?(Exwiw::QueryAst::SelectSubquery)

        inner_values = subquery.where_values.map { |v| escape_value(v) }
        "SELECT #{subquery.table_name}.#{subquery.select_column} " \
          "FROM #{subquery.table_name} " \
          "WHERE #{subquery.table_name}.#{subquery.where_column} IN (#{inner_values.join(', ')})"
      end

      private def escape_value(value)
        case value
        when nil
          "NULL"
        when String
          qv = escape_single_quote(value)
          "'#{qv}'"
        else
          value
        end
      end

      private def escape_single_quote(value)
        value.gsub("'", "''")
      end

      private def compile_column_name(ast, column)
        case column
        when Exwiw::QueryAst::ColumnValue::Plain
          "#{ast.from_table_name}.#{column.name}"
        when Exwiw::QueryAst::ColumnValue::RawSql
          column.value
        when Exwiw::QueryAst::ColumnValue::ReplaceWith
          parts = column.value.scan(/[^{}]+|\{[^{}]*\}/).map do |part|
            if part.start_with?('{')
              name = part[1..-2]
              "#{ast.from_table_name}.#{name}"
            else
              "'#{part}'"
            end
          end

          replaced = parts.join(", ")
          "CONCAT(#{replaced})"
        else
          raise "Unreachable case: #{column.inspect}"
        end
      end

      private def mariadb_mysqldump?(mysqldump_bin)
        return @mariadb_mysqldump if defined?(@mariadb_mysqldump)

        @mariadb_mysqldump =
          begin
            version_output, _, status = Open3.capture3(mysqldump_bin, '--version')
            status.success? && version_output.match?(/mariadb/i)
          rescue SystemCallError
            false
          end
      end

      private def connection
        @connection ||= MysqlClient.new(@connection_config)
      end
    end
  end
end
