# frozen_string_literal: true

module Exwiw
  module Adapter
    class PostgresqlAdapter < Base
      include SqlBulkInsert

      def build_query(table, dump_target, table_by_name)
        Exwiw::QueryAstBuilder.run(table.name, table_by_name, dump_target, @logger)
      end

      def execute(query_ast)
        sql = commented_sql(query_ast)

        @logger.debug("  Executing SQL: \n#{sql}")
        connection.exec(sql).values
      end

      def explain(query_ast)
        sql = commented_sql(query_ast)

        @logger.debug("  Executing EXPLAIN: \n#{sql}")
        connection.exec("EXPLAIN #{sql}").values.map(&:first).join("\n")
      end

      def dump_schema(ordered_tables, output_path)
        require 'open3'

        table_names = ordered_tables.map(&:name)
        if table_names.empty?
          File.write(output_path, "-- Auto-generated by exwiw. No tables in scope.\n")
          return
        end

        cmd = [
          'pg_dump',
          "--host=#{@connection_config.host}",
          "--port=#{@connection_config.port}",
          "--username=#{@connection_config.user}",
          '--schema-only',
          '--no-owner',
          '--no-acl',
          *table_names.flat_map { |t| ['--table', t] },
          @connection_config.database_name,
        ]
        env = { 'PGPASSWORD' => @connection_config.password.to_s }

        @logger.debug("  Running pg_dump for #{table_names.size} table(s)...")
        stdout, stderr, status = Open3.capture3(env, *cmd)
        unless status.success?
          if stderr.include?('command not found') || stderr.empty?
            raise "Failed to run `pg_dump`. Ensure the postgresql client is installed and on PATH. stderr: #{stderr}"
          end
          raise "pg_dump failed (exit #{status.exitstatus}): #{stderr}"
        end

        # Enums are prepended first, then extensions — so extensions end up at the top of the output.
        enum_types = query_enum_types(table_names)
        unless enum_types.empty?
          enum_ddl = DdlPostprocessor.create_type_enum_statements(enum_types)
          @logger.debug("  Found #{enum_types.size} enum type(s) to prepend.")
          stdout = enum_ddl + stdout
        end

        extensions = query_extensions
        unless extensions.empty?
          ext_ddl = extensions.map do |extname, schema|
            stmt = "CREATE EXTENSION IF NOT EXISTS #{connection.quote_ident(extname)}"
            stmt += " SCHEMA #{connection.quote_ident(schema)}" unless schema == "public"
            # Best-effort prepend: a restore target that genuinely cannot create the
            # extension should not abort the whole restore. Two such cases are caught:
            #   feature_not_supported (0A000) -- the extension's binaries are unavailable
            #   invalid_schema_name   (3F000) -- the extension's required schema is absent
            # insufficient_privilege (42501) is deliberately NOT caught: a restore role
            # lacking CREATE privilege is a misconfiguration to fix, not to skip silently.
            # The skip is re-raised as a WARNING so it surfaces in the restore logs
            # instead of vanishing.
            warning = connection.escape_literal("exwiw: skipped CREATE EXTENSION #{extname} (SQLSTATE %): %")
            "DO $$ BEGIN #{stmt}; " \
              "EXCEPTION WHEN feature_not_supported OR invalid_schema_name THEN " \
              "RAISE WARNING #{warning}, SQLSTATE, SQLERRM; END $$;"
          end.join("\n") + "\n\n"
          @logger.debug("  Found #{extensions.size} extension(s) to prepend.")
          stdout = ext_ddl + stdout
        end

        idempotent = stdout
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_schema(idempotent)
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_sequence(idempotent)
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_table(idempotent)
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_index(idempotent)
        idempotent = DdlPostprocessor.wrap_add_constraint_in_do_block(idempotent)
        idempotent = DdlPostprocessor.strip_triggers(idempotent)

        File.open(output_path, 'w') do |file|
          file.puts("-- Auto-generated by exwiw via pg_dump. Idempotent DDL for postgresql.")
          file.write(idempotent)
        end
        @logger.info("  Wrote schema for #{table_names.size} table(s) to #{output_path}.")
      end

      # The INSERT header for this adapter. PostgreSQL uses bare identifiers.
      # #to_bulk_insert / #write_inserts (SqlBulkInsert) append the value tuples
      # and the trailing `;`.
      private def insert_header(table)
        table_name = table.name
        if table.rails_managed?
          "INSERT INTO #{table_name} VALUES\n"
        else
          column_names = table.columns.map(&:name).join(', ')
          "INSERT INTO #{table_name} (#{column_names}) VALUES\n"
        end
      end

      def to_copy_from_stdin(results, table)
        header = if table.rails_managed?
                   "COPY #{table.name} FROM stdin;"
                 else
                   column_names = table.columns.map(&:name).join(', ')
                   "COPY #{table.name} (#{column_names}) FROM stdin;"
                 end
        lines = [header]
        results.each do |row|
          lines << row.map { |v| escape_copy_value(v) }.join("\t")
        end
        lines << '\\.'
        lines.join("\n")
      end

      # Transcribe the FROM-side sequence cursor backing `table.primary_key`
      # onto the import target. Without this, importing into a clean DB leaves
      # the sequence at 1 while the inserted rows occupy higher IDs, so the
      # next default-PK INSERT collides. We query FROM's `last_value` /
      # `is_called` directly (matching what pg_dump emits) rather than using
      # MAX(pk), so a subsetted dump still preserves the source's "next id".
      # Returns nil for non-auto-increment PKs (pg_get_serial_sequence -> NULL).
      #
      # Scope: ONLY the sequence attached to the primary key is synced. If a
      # table has additional auto-increment columns (e.g. a non-PK SERIAL),
      # those sequences are NOT transcribed and a subsequent default-value
      # INSERT on them can collide. Rails-managed schemas don't hit this
      # because only `id` is auto-increment, but bare PostgreSQL schemas may.
      def post_insert_sql(table)
        pk = table.primary_key
        return nil if pk.nil? || pk.empty?

        seq_name = connection
          .exec_params("SELECT pg_get_serial_sequence($1, $2)", [table.name, pk])
          .values.dig(0, 0)
        return nil if seq_name.nil?

        last_value, is_called = connection
          .exec("SELECT last_value, is_called FROM #{seq_name}")
          .values.first
        is_called_sql = (is_called == 't' || is_called == true) ? 'true' : 'false'

        "SELECT pg_catalog.setval('#{escape_single_quote(seq_name)}', #{last_value}, #{is_called_sql});"
      end

      def to_bulk_delete(select_query_ast, table)
        raise NotImplementedError unless select_query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "DELETE FROM #{select_query_ast.from_table_name}"

        if select_query_ast.join_clauses.empty?
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          compiled_where_conditions = select_query_ast.
            where_clauses.
            select { |where| where.is_a?(Exwiw::QueryAst::WhereClause) }.
            map do |where|
            compile_where_condition(where, select_query_ast.from_table_name)
          end

          if compiled_where_conditions.size > 0
            sql += "\nWHERE "
            sql += compiled_where_conditions.join(' AND ')
          end
          sql += ";"

          return sql
        end

        subquery_ast = Exwiw::QueryAst::Select.new
        first_join = select_query_ast.join_clauses.first.clone

        subquery_ast.from(first_join.join_table_name)
        primay_key_col = table.columns.find { |col| col.name == table.primary_key }
        subquery_ast.select([primay_key_col])
        select_query_ast.join_clauses[1..].each do |join|
          subquery_ast.join(join)
        end
        first_join.where_clauses.each do |where|
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          subquery_ast.where(where) if where.is_a?(Exwiw::QueryAst::WhereClause)
        end

        foreign_key = first_join.foreign_key
        outer_table = select_query_ast.from_table_name
        inner_table = first_join.join_table_name
        inner_column = first_join.primary_key
        cast_to = types_need_cast?(
          column_pg_type(outer_table, foreign_key),
          column_pg_type(inner_table, inner_column)
        ) ? 'text' : nil
        subquery_sql = compile_ast(subquery_ast, select_cast_to: cast_to)
        outer_expr = "#{outer_table}.#{foreign_key}"
        outer_expr = "#{outer_expr}::text" if cast_to
        sql += "\nWHERE #{outer_expr} IN (#{subquery_sql})"

        # first_join.base_where_clauses holds conditions on the outer
        # delete-target table (from_table_name), such as a polymorphic type
        # column. They are not part of the subquery, so add them to the outer
        # WHERE. This prevents deleting rows that belong to a different
        # polymorphic type.
        first_join.base_where_clauses.each do |where|
          next unless where.is_a?(Exwiw::QueryAst::WhereClause)

          sql += " AND #{compile_where_condition(where, select_query_ast.from_table_name)}"
        end
        sql += ";"

        sql
      end

      def compile_ast(query_ast, select_cast_to: nil)
        raise NotImplementedError unless query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "SELECT "
        sql += if query_ast.select_all
                 "*"
               else
                 cols = query_ast.columns.map { |col| compile_column_name(query_ast, col) }
                 cols = cols.map { |c| "#{c}::#{select_cast_to}" } if select_cast_to
                 cols.join(', ')
               end
        sql += " FROM #{query_ast.from_table_name}"

        query_ast.join_clauses.each do |join|
          fk_expr = "#{join.base_table_name}.#{join.foreign_key}"
          pk_expr = "#{join.join_table_name}.#{join.primary_key}"
          if types_need_cast?(
            column_pg_type(join.base_table_name, join.foreign_key),
            column_pg_type(join.join_table_name, join.primary_key)
          )
            fk_expr = "#{fk_expr}::text"
            pk_expr = "#{pk_expr}::text"
          end
          sql += " JOIN #{join.join_table_name} ON #{fk_expr} = #{pk_expr}"

          join.where_clauses.each do |where|
            compiled_where_condition = compile_where_condition(where, join.join_table_name)
            sql += " AND #{compiled_where_condition}"
          end

          # base_where_clauses is compiled against the joined-from table
          # (base_table_name), e.g. the type-column filter on a polymorphic
          # source table.
          join.base_where_clauses.each do |where|
            compiled_where_condition = compile_where_condition(where, join.base_table_name)
            sql += " AND #{compiled_where_condition}"
          end
        end

        if query_ast.where_clauses.any?
          sql += " WHERE "
          sql += query_ast.where_clauses.map { |where| compile_where_condition(where, query_ast.from_table_name) }.join(' AND ')
        end

        sql
      end

      private def compile_where_condition(where_clause, table_name)
        # Use as it is if it's a raw query
        return where_clause if where_clause.is_a?(String)

        key = "#{table_name}.#{where_clause.column_name}"

        if where_clause.operator == :eq
          values = where_clause.value.map { |v| escape_value(v) }

          if values.size == 1
            "#{key} = #{values.first}"
          else
            "#{key} IN (#{values.join(', ')})"
          end
        elsif where_clause.operator == :in_subquery
          subquery_sql = compile_subquery(where_clause.value, outer_table: table_name, outer_column: where_clause.column_name)
          cast_to = subquery_cast_to(where_clause.value, table_name, where_clause.column_name)
          outer_key = cast_to ? "#{key}::#{cast_to}" : key
          "#{outer_key} IN (#{subquery_sql})"
        else
          raise "Unsupported operator: #{where_clause.operator}"
        end
      end

      private def compile_subquery(subquery, outer_table: nil, outer_column: nil)
        cast_to = subquery_cast_to(subquery, outer_table, outer_column)

        if subquery.is_a?(Exwiw::QueryAst::SelectSubquery)
          return compile_ast(subquery.query, select_cast_to: cast_to)
        end

        inner_values = subquery.where_values.map { |v| escape_value(v) }
        select_expr = "#{subquery.table_name}.#{subquery.select_column}"
        select_expr = "#{select_expr}::#{cast_to}" if cast_to
        "SELECT #{select_expr} " \
          "FROM #{subquery.table_name} " \
          "WHERE #{subquery.table_name}.#{subquery.where_column} IN (#{inner_values.join(', ')})"
      end

      private def subquery_select_target(subquery)
        case subquery
        when Exwiw::QueryAst::SelectSubquery
          q = subquery.query
          col = q.columns.first
          col ? [q.from_table_name, col.name] : [nil, nil]
        when Exwiw::QueryAst::Subquery
          [subquery.table_name, subquery.select_column]
        else
          [nil, nil]
        end
      end

      private def subquery_cast_to(subquery, outer_table, outer_column)
        return nil if outer_table.nil? || outer_column.nil?

        inner_table, inner_column = subquery_select_target(subquery)
        return nil if inner_table.nil?

        outer_type = column_pg_type(outer_table, outer_column)
        inner_type = column_pg_type(inner_table, inner_column)
        types_need_cast?(outer_type, inner_type) ? 'text' : nil
      end

      private def escape_value(value)
        case value
        when nil
          "NULL"
        when String
          qv = escape_single_quote(value)
          "'#{qv}'"
        else
          value
        end
      end

      private def escape_copy_value(value)
        case value
        when nil
          "\\N"
        when String
          value
            .gsub('\\') { '\\\\' }
            .gsub("\t", '\t')
            .gsub("\n", '\n')
            .gsub("\r", '\r')
        else
          value.to_s
        end
      end

      private def escape_single_quote(value)
        value.gsub("'", "''")
      end

      private def compile_column_name(ast, column)
        case column
        when Exwiw::QueryAst::ColumnValue::Plain
          "#{ast.from_table_name}.#{column.name}"
        when Exwiw::QueryAst::ColumnValue::RawSql
          column.value
        when Exwiw::QueryAst::ColumnValue::ReplaceWith
          parts = column.value.scan(/[^{}]+|\{[^{}]*\}/).map do |part|
            if part.start_with?('{')
              name = part[1..-2]
              "#{ast.from_table_name}.#{name}"
            else
              "'#{part}'"
            end
          end

          replaced = parts.join(", ")
          "CONCAT(#{replaced})"
        else
          raise "Unreachable case: #{column.inspect}"
        end
      end

      private def query_extensions
        # Skip plpgsql (always present) and managed-platform bookkeeping extensions
        # (google_*/rds_*/aiven_*). pglogical is also skipped: it is a logical-
        # replication mechanism of the source, not part of the data being copied,
        # and its dedicated `pglogical` schema is typically absent on the restore
        # target — so prepending CREATE EXTENSION for it only breaks the restore.
        sql = <<~SQL
          SELECT e.extname, n.nspname
          FROM pg_extension e
          JOIN pg_namespace n ON n.oid = e.extnamespace
          WHERE e.extname != 'plpgsql'
            AND e.extname != 'pglogical'
            AND e.extname NOT LIKE 'google\\_%' ESCAPE '\\'
            AND e.extname NOT LIKE 'rds\\_%' ESCAPE '\\'
            AND e.extname NOT LIKE 'aiven\\_%' ESCAPE '\\'
          ORDER BY e.extname
        SQL
        connection.exec(sql).map { |row| [row["extname"], row["nspname"]] }
      end

      private def query_enum_types(table_names)
        return [] if table_names.empty?

        placeholders = table_names.each_with_index.map { |_, i| "$#{i + 1}" }.join(', ')
        sql = <<~SQL
          SELECT
            n.nspname  AS type_schema,
            t.typname  AS type_name,
            array_agg(e.enumlabel ORDER BY e.enumsortorder) AS enum_labels
          FROM pg_type t
          JOIN pg_namespace n ON n.oid = t.typnamespace
          JOIN pg_enum e      ON e.enumtypid = t.oid
          WHERE t.typtype = 'e'
            AND t.oid IN (
              SELECT a.atttypid
              FROM pg_attribute a
              JOIN pg_class c ON c.oid = a.attrelid
              WHERE c.relname IN (#{placeholders})
                AND a.attnum > 0
                AND NOT a.attisdropped
            )
          GROUP BY n.nspname, t.typname
          ORDER BY n.nspname, t.typname
        SQL

        result = connection.exec_params(sql, table_names)
        decoder = PG::TextDecoder::Array.new
        result.map do |row|
          {
            schema: row['type_schema'],
            name: row['type_name'],
            labels: decoder.decode(row['enum_labels']),
          }
        end
      end

      private def column_pg_type(table_name, column_name)
        @column_type_cache ||= {}
        cache_key = [table_name, column_name]
        return @column_type_cache[cache_key] if @column_type_cache.key?(cache_key)

        sql = <<~SQL
          SELECT t.typname
          FROM pg_attribute a
          JOIN pg_class c ON c.oid = a.attrelid
          JOIN pg_type t  ON t.oid = a.atttypid
          WHERE c.relname = $1
            AND a.attname = $2
            AND a.attnum > 0
            AND NOT a.attisdropped
          LIMIT 1
        SQL

        result = connection.exec_params(sql, [table_name, column_name])
        @column_type_cache[cache_key] = result.ntuples > 0 ? result.getvalue(0, 0) : nil
      end

      private def types_need_cast?(type_a, type_b)
        return false if type_a.nil? || type_b.nil?
        return false if type_a == type_b

        string_types = %w[varchar text bpchar name].freeze
        (type_a == 'uuid' && string_types.include?(type_b)) ||
          (type_b == 'uuid' && string_types.include?(type_a))
      end

      private def connection
        @connection ||=
          begin
            require 'pg'
            PG.connect(
              host: @connection_config.host,
              port: @connection_config.port,
              user: @connection_config.user,
              password: @connection_config.password,
              dbname: @connection_config.database_name
            )
          end
      end
    end
  end
end
