# frozen_string_literal: true

module Exwiw
  module Adapter
    class PostgresqlAdapter < Base
      def build_query(table, dump_target, table_by_name)
        Exwiw::QueryAstBuilder.run(table.name, table_by_name, dump_target, @logger)
      end

      def execute(query_ast)
        sql = commented_sql(query_ast)

        @logger.debug("  Executing SQL: \n#{sql}")
        connection.exec(sql).values
      end

      def explain(query_ast)
        sql = commented_sql(query_ast)

        @logger.debug("  Executing EXPLAIN: \n#{sql}")
        connection.exec("EXPLAIN #{sql}").values.map(&:first).join("\n")
      end

      def dump_schema(ordered_tables, output_path)
        require 'open3'

        table_names = ordered_tables.map(&:name)
        if table_names.empty?
          File.write(output_path, "-- Auto-generated by exwiw. No tables in scope.\n")
          return
        end

        cmd = [
          'pg_dump',
          "--host=#{@connection_config.host}",
          "--port=#{@connection_config.port}",
          "--username=#{@connection_config.user}",
          '--schema-only',
          '--no-owner',
          '--no-acl',
          *table_names.flat_map { |t| ['--table', t] },
          @connection_config.database_name,
        ]
        env = { 'PGPASSWORD' => @connection_config.password.to_s }

        @logger.debug("  Running pg_dump for #{table_names.size} table(s)...")
        stdout, stderr, status = Open3.capture3(env, *cmd)
        unless status.success?
          if stderr.include?('command not found') || stderr.empty?
            raise "Failed to run `pg_dump`. Ensure the postgresql client is installed and on PATH. stderr: #{stderr}"
          end
          raise "pg_dump failed (exit #{status.exitstatus}): #{stderr}"
        end

        enum_types = query_enum_types(table_names)
        unless enum_types.empty?
          enum_ddl = DdlPostprocessor.create_type_enum_statements(enum_types)
          @logger.debug("  Found #{enum_types.size} enum type(s) to prepend.")
          stdout = enum_ddl + stdout
        end

        idempotent = stdout
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_schema(idempotent)
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_sequence(idempotent)
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_table(idempotent)
        idempotent = DdlPostprocessor.add_if_not_exists_to_create_index(idempotent)
        idempotent = DdlPostprocessor.wrap_add_constraint_in_do_block(idempotent)

        File.open(output_path, 'w') do |file|
          file.puts("-- Auto-generated by exwiw via pg_dump. Idempotent DDL for postgresql.")
          file.write(idempotent)
        end
        @logger.info("  Wrote schema for #{table_names.size} table(s) to #{output_path}.")
      end

      def to_bulk_insert(results, table)
        table_name = table.name

        value_list = results.map do |row|
          quoted_values = row.map do |value|
            escape_value(value)
          end
          "(" + quoted_values.join(', ') + ")"
        end
        values = value_list.join(",\n")

        if table.rails_managed?
          "INSERT INTO #{table_name} VALUES\n#{values};"
        else
          column_names = table.columns.map(&:name).join(', ')
          "INSERT INTO #{table_name} (#{column_names}) VALUES\n#{values};"
        end
      end

      def to_copy_from_stdin(results, table)
        header = if table.rails_managed?
                   "COPY #{table.name} FROM stdin;"
                 else
                   column_names = table.columns.map(&:name).join(', ')
                   "COPY #{table.name} (#{column_names}) FROM stdin;"
                 end
        lines = [header]
        results.each do |row|
          lines << row.map { |v| escape_copy_value(v) }.join("\t")
        end
        lines << '\\.'
        lines.join("\n")
      end

      # Transcribe the FROM-side sequence cursor backing `table.primary_key`
      # onto the import target. Without this, importing into a clean DB leaves
      # the sequence at 1 while the inserted rows occupy higher IDs, so the
      # next default-PK INSERT collides. We query FROM's `last_value` /
      # `is_called` directly (matching what pg_dump emits) rather than using
      # MAX(pk), so a subsetted dump still preserves the source's "next id".
      # Returns nil for non-auto-increment PKs (pg_get_serial_sequence -> NULL).
      #
      # Scope: ONLY the sequence attached to the primary key is synced. If a
      # table has additional auto-increment columns (e.g. a non-PK SERIAL),
      # those sequences are NOT transcribed and a subsequent default-value
      # INSERT on them can collide. Rails-managed schemas don't hit this
      # because only `id` is auto-increment, but bare PostgreSQL schemas may.
      def post_insert_sql(table)
        pk = table.primary_key
        return nil if pk.nil? || pk.empty?

        seq_name = connection
          .exec_params("SELECT pg_get_serial_sequence($1, $2)", [table.name, pk])
          .values.dig(0, 0)
        return nil if seq_name.nil?

        last_value, is_called = connection
          .exec("SELECT last_value, is_called FROM #{seq_name}")
          .values.first
        is_called_sql = (is_called == 't' || is_called == true) ? 'true' : 'false'

        "SELECT pg_catalog.setval('#{escape_single_quote(seq_name)}', #{last_value}, #{is_called_sql});"
      end

      def to_bulk_delete(select_query_ast, table)
        raise NotImplementedError unless select_query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "DELETE FROM #{select_query_ast.from_table_name}"

        if select_query_ast.join_clauses.empty?
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          compiled_where_conditions = select_query_ast.
            where_clauses.
            select { |where| where.is_a?(Exwiw::QueryAst::WhereClause) }.
            map do |where|
            compile_where_condition(where, select_query_ast.from_table_name)
          end

          if compiled_where_conditions.size > 0
            sql += "\nWHERE "
            sql += compiled_where_conditions.join(' AND ')
          end
          sql += ";"

          return sql
        end

        subquery_ast = Exwiw::QueryAst::Select.new
        first_join = select_query_ast.join_clauses.first.clone

        subquery_ast.from(first_join.join_table_name)
        primay_key_col = table.columns.find { |col| col.name == table.primary_key }
        subquery_ast.select([primay_key_col])
        select_query_ast.join_clauses[1..].each do |join|
          subquery_ast.join(join)
        end
        first_join.where_clauses.each do |where|
          # Ignore filter option, because bulk delete is for cleaning before import,
          # so it should delete all records to avoid foreign key violation & data consistancy.
          subquery_ast.where(where) if where.is_a?(Exwiw::QueryAst::WhereClause)
        end

        foreign_key = first_join.foreign_key
        subquery_sql = compile_ast(subquery_ast)
        sql += "\nWHERE #{select_query_ast.from_table_name}.#{foreign_key} IN (#{subquery_sql})"

        # first_join.base_where_clauses は外側の削除対象テーブル
        # (from_table_name) 上の条件 (polymorphic 型カラム等)。subquery には
        # 含まれないため、外側の WHERE に追加する。これにより、別の
        # polymorphic 型に属する行まで削除してしまうのを防ぐ。
        first_join.base_where_clauses.each do |where|
          next unless where.is_a?(Exwiw::QueryAst::WhereClause)

          sql += " AND #{compile_where_condition(where, select_query_ast.from_table_name)}"
        end
        sql += ";"

        sql
      end

      def compile_ast(query_ast)
        raise NotImplementedError unless query_ast.is_a?(Exwiw::QueryAst::Select)

        sql = "SELECT "
        sql += if query_ast.select_all
                 "*"
               else
                 query_ast.columns.map { |col| compile_column_name(query_ast, col) }.join(', ')
               end
        sql += " FROM #{query_ast.from_table_name}"

        query_ast.join_clauses.each do |join|
          sql += " JOIN #{join.join_table_name} ON #{join.base_table_name}.#{join.foreign_key} = #{join.join_table_name}.#{join.primary_key}"

          join.where_clauses.each do |where|
            compiled_where_condition = compile_where_condition(where, join.join_table_name)
            sql += " AND #{compiled_where_condition}"
          end

          # base_where_clauses は結合元テーブル (base_table_name) に対して
          # コンパイルする。polymorphic な結合元テーブルの型カラム絞り込み等。
          join.base_where_clauses.each do |where|
            compiled_where_condition = compile_where_condition(where, join.base_table_name)
            sql += " AND #{compiled_where_condition}"
          end
        end

        if query_ast.where_clauses.any?
          sql += " WHERE "
          sql += query_ast.where_clauses.map { |where| compile_where_condition(where, query_ast.from_table_name) }.join(' AND ')
        end

        sql
      end

      private def compile_where_condition(where_clause, table_name)
        # Use as it is if it's a raw query
        return where_clause if where_clause.is_a?(String)

        key = "#{table_name}.#{where_clause.column_name}"

        if where_clause.operator == :eq
          values = where_clause.value.map { |v| escape_value(v) }

          if values.size == 1
            "#{key} = #{values.first}"
          else
            "#{key} IN (#{values.join(', ')})"
          end
        else
          raise "Unsupported operator: #{where_clause.operator}"
        end
      end

      private def escape_value(value)
        case value
        when nil
          "NULL"
        when String
          qv = escape_single_quote(value)
          "'#{qv}'"
        else
          value
        end
      end

      private def escape_copy_value(value)
        case value
        when nil
          "\\N"
        when String
          value
            .gsub('\\') { '\\\\' }
            .gsub("\t", '\t')
            .gsub("\n", '\n')
            .gsub("\r", '\r')
        else
          value.to_s
        end
      end

      private def escape_single_quote(value)
        value.gsub("'", "''")
      end

      private def compile_column_name(ast, column)
        case column
        when Exwiw::QueryAst::ColumnValue::Plain
          "#{ast.from_table_name}.#{column.name}"
        when Exwiw::QueryAst::ColumnValue::RawSql
          column.value
        when Exwiw::QueryAst::ColumnValue::ReplaceWith
          parts = column.value.scan(/[^{}]+|\{[^{}]*\}/).map do |part|
            if part.start_with?('{')
              name = part[1..-2]
              "#{ast.from_table_name}.#{name}"
            else
              "'#{part}'"
            end
          end

          replaced = parts.join(", ")
          "CONCAT(#{replaced})"
        else
          raise "Unreachable case: #{column.inspect}"
        end
      end

      private def query_enum_types(table_names)
        return [] if table_names.empty?

        placeholders = table_names.each_with_index.map { |_, i| "$#{i + 1}" }.join(', ')
        sql = <<~SQL
          SELECT DISTINCT
            n.nspname  AS type_schema,
            t.typname  AS type_name,
            array_agg(e.enumlabel ORDER BY e.enumsortorder) AS enum_labels
          FROM pg_attribute a
          JOIN pg_class c      ON c.oid = a.attrelid
          JOIN pg_namespace cn ON cn.oid = c.relnamespace
          JOIN pg_type t       ON t.oid = a.atttypid
          JOIN pg_namespace n  ON n.oid = t.typnamespace
          JOIN pg_enum e       ON e.enumtypid = t.oid
          WHERE c.relname IN (#{placeholders})
            AND a.attnum > 0
            AND NOT a.attisdropped
            AND t.typtype = 'e'
          GROUP BY n.nspname, t.typname
          ORDER BY n.nspname, t.typname
        SQL

        result = connection.exec_params(sql, table_names)
        decoder = PG::TextDecoder::Array.new
        result.map do |row|
          {
            schema: row['type_schema'],
            name: row['type_name'],
            labels: decoder.decode(row['enum_labels']),
          }
        end
      end

      private def connection
        @connection ||=
          begin
            require 'pg'
            PG.connect(
              host: @connection_config.host,
              port: @connection_config.port,
              user: @connection_config.user,
              password: @connection_config.password,
              dbname: @connection_config.database_name
            )
          end
      end
    end
  end
end
