# frozen_string_literal: true

module Exwiw
  # Paired (kanji, katakana) Japanese name data for the `ja` locale of the
  # person-family `replace_with_fake_data` types (see {RowTransformer}).
  #
  # faker's `ja` locale ships kanji names only, with no reading, so it cannot
  # produce kana (フリガナ) at all, and its last_name / first_name pools are
  # unrelated to each other. exwiw bundles this paired dataset instead so that:
  #
  # - a fake person carries a kana reading that actually matches its kanji, and
  # - last_name / first_name / full name (and their kana) for a single seed all
  #   come from the same person (a coherent identity).
  #
  # The kanji sets mirror faker's `ja` name list (100 surnames, 100 given names)
  # so coverage matches faker; exwiw adds the readings. 100 x 100 = 10,000
  # combinations equals the person pool size (RowTransformer::POOL_SIZE), so the
  # pool spans the full name space rather than repeating a small subset.
  #
  # Readings are katakana (matching the katakana convention of typical `*_kana`
  # columns). They are plausible common readings, not the only possible reading
  # of each kanji — fake data only needs to look real, not be canonical.
  module JapaneseNames
    SURNAMES = [
      %w[佐藤 サトウ],
      %w[鈴木 スズキ],
      %w[高橋 タカハシ],
      %w[田中 タナカ],
      %w[伊藤 イトウ],
      %w[山本 ヤマモト],
      %w[渡辺 ワタナベ],
      %w[中村 ナカムラ],
      %w[小林 コバヤシ],
      %w[加藤 カトウ],
      %w[吉田 ヨシダ],
      %w[山田 ヤマダ],
      %w[佐々木 ササキ],
      %w[山口 ヤマグチ],
      %w[松本 マツモト],
      %w[井上 イノウエ],
      %w[木村 キムラ],
      %w[林 ハヤシ],
      %w[斎藤 サイトウ],
      %w[清水 シミズ],
      %w[山崎 ヤマザキ],
      %w[阿部 アベ],
      %w[森 モリ],
      %w[池田 イケダ],
      %w[橋本 ハシモト],
      %w[山下 ヤマシタ],
      %w[石川 イシカワ],
      %w[中島 ナカジマ],
      %w[前田 マエダ],
      %w[藤田 フジタ],
      %w[後藤 ゴトウ],
      %w[小川 オガワ],
      %w[岡田 オカダ],
      %w[村上 ムラカミ],
      %w[長谷川 ハセガワ],
      %w[近藤 コンドウ],
      %w[石井 イシイ],
      %w[斉藤 サイトウ],
      %w[坂本 サカモト],
      %w[遠藤 エンドウ],
      %w[藤井 フジイ],
      %w[青木 アオキ],
      %w[福田 フクダ],
      %w[三浦 ミウラ],
      %w[西村 ニシムラ],
      %w[藤原 フジワラ],
      %w[太田 オオタ],
      %w[松田 マツダ],
      %w[原田 ハラダ],
      %w[岡本 オカモト],
      %w[中野 ナカノ],
      %w[中川 ナカガワ],
      %w[小野 オノ],
      %w[田村 タムラ],
      %w[竹内 タケウチ],
      %w[金子 カネコ],
      %w[中山 ナカヤマ],
      %w[和田 ワダ],
      %w[石田 イシダ],
      %w[工藤 クドウ],
      %w[上田 ウエダ],
      %w[原 ハラ],
      %w[森田 モリタ],
      %w[酒井 サカイ],
      %w[横山 ヨコヤマ],
      %w[柴田 シバタ],
      %w[宮崎 ミヤザキ],
      %w[宮本 ミヤモト],
      %w[内田 ウチダ],
      %w[高木 タカギ],
      %w[谷口 タニグチ],
      %w[安藤 アンドウ],
      %w[丸山 マルヤマ],
      %w[今井 イマイ],
      %w[大野 オオノ],
      %w[高田 タカダ],
      %w[菅原 スガワラ],
      %w[河野 コウノ],
      %w[武田 タケダ],
      %w[藤本 フジモト],
      %w[上野 ウエノ],
      %w[杉山 スギヤマ],
      %w[千葉 チバ],
      %w[村田 ムラタ],
      %w[増田 マスダ],
      %w[小島 コジマ],
      %w[小山 コヤマ],
      %w[大塚 オオツカ],
      %w[平野 ヒラノ],
      %w[久保 クボ],
      %w[渡部 ワタナベ],
      %w[松井 マツイ],
      %w[菊地 キクチ],
      %w[岩崎 イワサキ],
      %w[松尾 マツオ],
      %w[佐野 サノ],
      %w[木下 キノシタ],
      %w[野口 ノグチ],
      %w[野村 ノムラ],
      %w[新井 アライ],
    ].freeze

    GIVEN_NAMES = [
      %w[翔太 ショウタ],
      %w[蓮 レン],
      %w[翔 ショウ],
      %w[陸 リク],
      %w[颯太 ソウタ],
      %w[悠斗 ユウト],
      %w[大翔 ヒロト],
      %w[翼 ツバサ],
      %w[樹 イツキ],
      %w[奏太 ソウタ],
      %w[大和 ヤマト],
      %w[大輝 ダイキ],
      %w[悠 ユウ],
      %w[隼人 ハヤト],
      %w[健太 ケンタ],
      %w[大輔 ダイスケ],
      %w[駿 シュン],
      %w[陽斗 ハルト],
      %w[優 ユウ],
      %w[陽 ヨウ],
      %w[悠人 ユウト],
      %w[誠 マコト],
      %w[拓海 タクミ],
      %w[仁 ジン],
      %w[悠太 ユウタ],
      %w[悠真 ユウマ],
      %w[大地 ダイチ],
      %w[健 ケン],
      %w[遼 リョウ],
      %w[大樹 ダイキ],
      %w[諒 リョウ],
      %w[響 ヒビキ],
      %w[太一 タイチ],
      %w[一郎 イチロウ],
      %w[優斗 ユウト],
      %w[亮 リョウ],
      %w[海斗 カイト],
      %w[颯 ソウ],
      %w[亮太 リョウタ],
      %w[匠 タクミ],
      %w[陽太 ヨウタ],
      %w[航 ワタル],
      %w[瑛太 エイタ],
      %w[直樹 ナオキ],
      %w[空 ソラ],
      %w[光 ヒカル],
      %w[太郎 タロウ],
      %w[輝 ヒカル],
      %w[一輝 カズキ],
      %w[蒼 アオイ],
      %w[葵 アオイ],
      %w[優那 ユウナ],
      %w[優奈 ユウナ],
      %w[凛 リン],
      %w[陽菜 ヒナ],
      %w[愛 アイ],
      %w[結衣 ユイ],
      %w[美咲 ミサキ],
      %w[楓 カエデ],
      %w[さくら サクラ],
      %w[遥 ハルカ],
      %w[美優 ミユ],
      %w[莉子 リコ],
      %w[七海 ナナミ],
      %w[美月 ミヅキ],
      %w[結菜 ユナ],
      %w[真央 マオ],
      %w[花音 カノン],
      %w[陽子 ヨウコ],
      %w[舞 マイ],
      %w[美羽 ミウ],
      %w[優衣 ユイ],
      %w[未来 ミク],
      %w[彩 アヤ],
      %w[彩乃 アヤノ],
      %w[彩花 アヤカ],
      %w[智子 トモコ],
      %w[奈々 ナナ],
      %w[千尋 チヒロ],
      %w[愛美 マナミ],
      %w[優菜 ユウナ],
      %w[杏 アン],
      %w[裕子 ユウコ],
      %w[芽衣 メイ],
      %w[綾乃 アヤノ],
      %w[琴音 コトネ],
      %w[桜 サクラ],
      %w[恵 メグミ],
      %w[杏奈 アンナ],
      %w[美桜 ミオ],
      %w[優花 ユウカ],
      %w[玲奈 レナ],
      %w[結 ユイ],
      %w[茜 アカネ],
      %w[美穂 ミホ],
      %w[明日香 アスカ],
      %w[愛子 アイコ],
      %w[美緒 ミオ],
      %w[千夏 チナツ],
      %w[真希 マキ],
    ].freeze
  end
end
