# frozen_string_literal: true

module Exwiw
  # Paired (kanji, katakana) Japanese name data for the `ja` locale of the
  # person-family `replace_with_fake_data` types (see {RowTransformer}).
  #
  # faker's `ja` locale ships kanji names only, with no reading, so it cannot
  # produce kana (フリガナ) at all, and its last_name / first_name pools are
  # unrelated to each other. exwiw bundles this paired dataset instead so that:
  #
  # - a fake person carries a kana reading that actually matches its kanji, and
  # - last_name / first_name / full name (and their kana) for a single seed all
  #   come from the same person (a coherent identity).
  #
  # Readings are katakana (matching the katakana convention of typical `*_kana`
  # columns). They are plausible common readings, not the only possible reading
  # of each kanji — fake data only needs to look real, not be canonical.
  module JapaneseNames
    SURNAMES = [
      %w[佐藤 サトウ],
      %w[鈴木 スズキ],
      %w[高橋 タカハシ],
      %w[田中 タナカ],
      %w[伊藤 イトウ],
      %w[山本 ヤマモト],
      %w[渡辺 ワタナベ],
      %w[中村 ナカムラ],
      %w[小林 コバヤシ],
      %w[加藤 カトウ],
      %w[吉田 ヨシダ],
      %w[山田 ヤマダ],
      %w[佐々木 ササキ],
      %w[山口 ヤマグチ],
      %w[松本 マツモト],
      %w[井上 イノウエ],
      %w[木村 キムラ],
      %w[林 ハヤシ],
      %w[斎藤 サイトウ],
      %w[清水 シミズ],
      %w[山崎 ヤマザキ],
      %w[阿部 アベ],
      %w[森 モリ],
      %w[池田 イケダ],
      %w[橋本 ハシモト],
      %w[山下 ヤマシタ],
      %w[石川 イシカワ],
      %w[中島 ナカジマ],
      %w[前田 マエダ],
      %w[藤田 フジタ],
      %w[後藤 ゴトウ],
      %w[小川 オガワ],
      %w[岡田 オカダ],
      %w[村上 ムラカミ],
      %w[長谷川 ハセガワ],
      %w[近藤 コンドウ],
      %w[石井 イシイ],
      %w[坂本 サカモト],
      %w[遠藤 エンドウ],
      %w[藤井 フジイ],
      %w[青木 アオキ],
      %w[福田 フクダ],
      %w[三浦 ミウラ],
      %w[西村 ニシムラ],
      %w[藤原 フジワラ],
      %w[太田 オオタ],
      %w[松田 マツダ],
      %w[原田 ハラダ],
      %w[岡本 オカモト],
      %w[中野 ナカノ],
      %w[中川 ナカガワ],
      %w[小野 オノ],
      %w[田村 タムラ],
      %w[竹内 タケウチ],
      %w[金子 カネコ],
      %w[中山 ナカヤマ],
      %w[和田 ワダ],
      %w[石田 イシダ],
      %w[森田 モリタ],
      %w[酒井 サカイ]
    ].freeze

    GIVEN_NAMES = [
      %w[翔太 ショウタ],
      %w[蓮 レン],
      %w[大翔 ヒロト],
      %w[陸 リク],
      %w[颯太 ソウタ],
      %w[悠斗 ユウト],
      %w[翼 ツバサ],
      %w[樹 イツキ],
      %w[大和 ヤマト],
      %w[大輝 ダイキ],
      %w[隼人 ハヤト],
      %w[健太 ケンタ],
      %w[大輔 ダイスケ],
      %w[駿 シュン],
      %w[陽斗 ハルト],
      %w[拓海 タクミ],
      %w[仁 ジン],
      %w[悠太 ユウタ],
      %w[大地 ダイチ],
      %w[健 ケン],
      %w[遼 リョウ],
      %w[響 ヒビキ],
      %w[一郎 イチロウ],
      %w[海斗 カイト],
      %w[亮太 リョウタ],
      %w[航 ワタル],
      %w[直樹 ナオキ],
      %w[空 ソラ],
      %w[光 ヒカル],
      %w[太郎 タロウ],
      %w[蒼 アオイ],
      %w[葵 アオイ],
      %w[凛 リン],
      %w[陽菜 ヒナ],
      %w[愛 アイ],
      %w[結衣 ユイ],
      %w[美咲 ミサキ],
      %w[楓 カエデ],
      %w[さくら サクラ],
      %w[遥 ハルカ],
      %w[美優 ミユ],
      %w[莉子 リコ],
      %w[七海 ナナミ],
      %w[美月 ミヅキ],
      %w[結菜 ユナ],
      %w[真央 マオ],
      %w[花音 カノン],
      %w[舞 マイ],
      %w[美羽 ミウ],
      %w[未来 ミライ],
      %w[彩 アヤ],
      %w[智子 トモコ],
      %w[千尋 チヒロ],
      %w[杏 アン],
      %w[桜 サクラ],
      %w[恵 メグミ],
      %w[玲奈 レナ],
      %w[茜 アカネ],
      %w[美穂 ミホ],
      %w[愛子 アイコ],
      %w[美緒 ミオ]
    ].freeze
  end
end
